spring:
  
  # JSP
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  # Reload
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
#  thymeleaf:
#    cache: false

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false